name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: PHP TOOLS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.0.19"

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: pmmp/setup-php-action@82a44d659bf5046612c69f036af3e14dc32e3fa8
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"

      - name: Restore Composer package cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install PHPStan Composer dependencies
        run: composer install --prefer-dist --no-interaction
      - name: Setup Code Style Checks
        uses: shivammathur/setup-php@2.22.0
        with:
          php-version: 8.0
          tools: php-cs-fixer:3.11
      - name: Run Code Style Checks
        continue-on-error: true # e
        run: php-cs-fixer fix src --dry-run --diff --ansi
      - name: Run PHPStan
        continue-on-error: true # phpstan level 9 (worst)
        run: vendor/bin/phpstan analyze
